paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: Products were got correctly.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Internal server error.
    post:
      summary: Post a product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        "200":
          description: Product was created correctly.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Internal server error.
  /api/products/{pid}:
    get:
      summary: Get a product by ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the product id that we want to get
          schema:
            $type: string
      responses:
        "200":
          description: The product was got correctly.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "400":
          description: ID not found.
    put:
      summary: Update a product by ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the product id that we want to update
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        "200":
          description: The product was updated correctly.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "400":
          description: ID not found.
    delete:
      summary: Delete a product by ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: pid is the product id that we want to delete
          schema:
            $type: string
      responses:
        "200":
          description: The product was deleted correctly.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "400":
          description: ID not found.

components:
  schemas:
    Product:
      type: Object
      properties:
        _id:
          type: ObjectId
          description: autogenerated ID by mongo
        title: 
          type: String
          description: unique title
        description:
          type: String
          description: description
        price: 
          type: Number
          description: price
        thumbnail:
          type: String
          description: profile picture
        code: 
          type: String
          desciption: unique and autogenerated code
        stock: 
          type: Number
          description: items amount
        category: 
          type: String
          description: category
        owner: 
          type: ObjectId
          description: product creator
        status:
          type: Boolean
          description: availability
  requestBodies:
    updateProduct:
      type: Object
      properties:
        title:
          type: String
          description: unique title
        price: 
          type: Number
          description: price
        code: 
          type: String
          desciption: unique and autogenerated code
        category: 
          type: String
          description: category